// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TomateTwitchBot.Data;

#nullable disable

namespace TomateTwitchBot.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240719151333_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("TomateTwitchBot.Data.Models.TimeoutDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Date")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KillerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Roll")
                        .HasColumnType("REAL");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VictimId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KillerId");

                    b.HasIndex("VictimId");

                    b.ToTable("Timeouts");
                });

            modelBuilder.Entity("TomateTwitchBot.Data.Models.UserDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSeenUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TomateTwitchBot.Data.Models.TimeoutDb", b =>
                {
                    b.HasOne("TomateTwitchBot.Data.Models.UserDb", "Killer")
                        .WithMany("Killed")
                        .HasForeignKey("KillerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TomateTwitchBot.Data.Models.UserDb", "Victim")
                        .WithMany("Died")
                        .HasForeignKey("VictimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Killer");

                    b.Navigation("Victim");
                });

            modelBuilder.Entity("TomateTwitchBot.Data.Models.UserDb", b =>
                {
                    b.Navigation("Died");

                    b.Navigation("Killed");
                });
#pragma warning restore 612, 618
        }
    }
}
